import { c as create_ssr_component } from "../../../chunks/ssr.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: 'h2.svelte-8dere5.svelte-8dere5{font-weight:600}.contact-section.svelte-8dere5.svelte-8dere5{height:calc(120vh - 68px);display:flex;flex-direction:column;justify-content:center;align-items:center;width:100%;background-image:url("$lib/assets/Homepage-4.webp"),\r\n      linear-gradient(to bottom, white, var(--lightblue), white 35%);background-size:cover;background-repeat:no-repeat}.hero-container.svelte-8dere5.svelte-8dere5{display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;margin:auto;gap:1em;width:85%}.form-container.svelte-8dere5.svelte-8dere5{width:100%;padding:0 0 7em 0}.hidden-field.svelte-8dere5.svelte-8dere5{position:absolute;left:-9999px;height:0;width:0;overflow:hidden}form.svelte-8dere5.svelte-8dere5{display:grid;grid-template-columns:1fr;grid-template-rows:auto;grid-template-areas:"email"\r\n      "phone-number"\r\n      "first-name"\r\n      "last-name"\r\n      "textarea"\r\n      "btn-container";text-align:center;gap:2em;margin:0 auto;width:80%}form.svelte-8dere5 input.svelte-8dere5,form.svelte-8dere5 textarea.svelte-8dere5{padding:1em;width:100%;font-size:1em;border-radius:4px;border-style:solid;border-width:1px}.submit-btn-container.svelte-8dere5.svelte-8dere5{grid-area:btn-container;display:flex;justify-content:center;align-items:center}.submit-btn.svelte-8dere5.svelte-8dere5{width:35%;margin:auto;box-shadow:none;background-color:var(--green);color:white;padding:0.5em 0;font-weight:bold;font-size:1em}.email.svelte-8dere5.svelte-8dere5{grid-area:email}.phone-number.svelte-8dere5.svelte-8dere5{grid-area:phone-number}.last-name.svelte-8dere5.svelte-8dere5{grid-area:last-name}.first-name.svelte-8dere5.svelte-8dere5{grid-area:first-name}.textarea.svelte-8dere5.svelte-8dere5{grid-area:textarea}@media(min-width: 768px){.contact-section.svelte-8dere5.svelte-8dere5{background-image:url("$lib/assets/Homepage-4.webp"),\r\n        linear-gradient(to bottom, white 5%, var(--lightblue), white 50%)}h2.svelte-8dere5.svelte-8dere5{font-size:2.5rem;font-weight:600}p.svelte-8dere5.svelte-8dere5{font-size:1.5rem}form.svelte-8dere5.svelte-8dere5{max-width:900px;grid-template-columns:repeat(2, 1fr);grid-template-rows:auto;grid-template-areas:"email phone-number"\r\n        "first-name last-name"\r\n        "textarea textarea"\r\n        "btn-container btn-container"}.submit-btn.svelte-8dere5.svelte-8dere5{width:25%}}',
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-1bex03k_START -->${$$result.title = `<title>FoundTech | Contact</title>`, ""}<meta name="keywords" content="ERP, Business tools, Management, Software, Application, Planning, CRM, Job, Management, Manufacturing, Profitability, Inventory, Efficiency, FullVue, FoundTech, Foundational Technologies"><meta name="description" content="Foundational Technologies LLC offers a cloud-based ERP app to help improve profitability and grow small businesses. Contact us about FullVue!"><!-- HEAD_svelte-1bex03k_END -->`, ""} <div data-svelte-h="svelte-n39ctp"><section class="contact-section svelte-8dere5"><div class="hero-container svelte-8dere5"><h2 class="svelte-8dere5">Reach out for your custom software solution</h2> <p class="svelte-8dere5">Fill out the form below to talk to our solutions team to see how we can
        help solve your business problems with software.</p></div> <div class="form-container svelte-8dere5"><form name="contact" method="POST" data-netlify="true" netlify-honeypot="bot-field" action="/thank-you" class="svelte-8dere5"><input type="hidden" name="form-name" value="contact" class="svelte-8dere5"> <p class="hidden-field svelte-8dere5" aria-hidden="true"><label>Don&#39;t fill this out if you&#39;re human: <input name="bot-field" class="svelte-8dere5"></label></p> <input type="email" class="email svelte-8dere5" name="businessEmail" placeholder="Email*" aria-label="Email" required> <input type="tel" class="phone-number svelte-8dere5" name="phoneNumber" placeholder="Phone Number (optional)" aria-label="Phone number (optional)"> <input type="text" class="first-name svelte-8dere5" name="firstName" placeholder="First Name*" aria-label="First name" required> <input type="text" class="last-name svelte-8dere5" name="lastName" placeholder="Last Name*" aria-label="Last name" required> <div class="textarea svelte-8dere5"> <textarea name="message" id="message" cols="30" rows="5" placeholder="Message" aria-label="Message" class="svelte-8dere5"></textarea></div> <div class="submit-btn-container svelte-8dere5"><input class="submit-btn svelte-8dere5" type="submit" value="Submit"></div></form></div></section> </div>`;
});
export {
  Page as default
};
